from django.urls import path
from hotel_app.views import (
    HotelRegister,
    ViewHotelRoomDetails,
    AdminViewRoomDetails,
    ViewRoomDetailsById,
    EditHotelDetails,
    GetHotelDetails,
    HotelDetailsByStatus,
    ApproveHotel,
    RejectHotel,
    ViewHotel,
    SuspendHotel,
    DeleteHotel,
    AddRoomType,
    ListRoomTypes,
    AddRoomDetails,
    RoomDetailsByStatus,
    EditRoomDetails,
    BookingHotelRoom,
    GetCustomerBookings,
    ListHotelRoomDetails,
    ReviewView,
    GetReviewView,
    UpdateReview,
    DeleteHotelAccount,
    ListActiveHotelDetails,
    HotelSearchView,
    GetRoomTypes,
    DeleteRoomDetails,
    BookingPaymentDetails,
    PaymentInvoiceDetails,
    AddRoomServices,
    AddFeedbacksByHotels,
    ListFeedbacksByHotels,
    ViewRoomServices,
    ListBookings,
    SortBooking,
    RoomAdditionalActivitesView,
    ViewAdditionalActivitesByHotel,
    ViewActivitiesAddedToRooms,
    ViewActivitiesAddedToRoomsByHotels,
    DeleteServicesAddedToRooms,
    DeleteReview,
    EditRoomServices,
    DeleteRoomServices,
    ActivateHotel,
    PaymentCalculation,
    PaymentConfirmation,
    StripePaymentCheckout,
    ViewPaymentDetails,
    ViewServicesById,
    CustomerReservationList,
    SortCustomerReservation,
    CountTodayBooking,
    PaymentPercentage,
    GetSelectedWeekBookings,
    RecentReviews,
    ReviewsListByHotelId,
    CancelBookings,
    RoomAndServicesCount,
    CancelIncompleteBookings,
    SortActiveHotelDetails,
    HotelNotifications,
    DeleteHotelNotifications,
    AddHotelNotificationToFavorites,
    ReadHotelnotification,
    UnreadHotelNotificationCount


)
    

urlpatterns = [
    path('hotel-register/',HotelRegister.as_view(), name='hotel-register'),
    path('hotel-details/',GetHotelDetails.as_view(), name='hotel-details'),
    path('hotels-by-status/<str:hotelstatus>/',HotelDetailsByStatus.as_view(), name='hotels-by-status'),
    path('approve-hotel/<int:id>/',ApproveHotel.as_view(), name='approve-hotel'),
    path('reject-hotel/<int:id>/',RejectHotel.as_view(), name='reject-hotel'),
    path('view-hotel/<int:id>/',ViewHotel.as_view(), name='view-hotel'),
    path('suspend-hotel/<int:id>/',SuspendHotel.as_view(), name='suspend-hotel'),
    path('delete-hotel/<int:id>/',DeleteHotel.as_view(), name='delete-hotel'),
    path('add-room-type/', AddRoomType.as_view(), name='add-room-type'),
    path('list-room-types/', ListRoomTypes.as_view(), name='list-room-types'),
    path('delete-hotel-account/<int:id>/', DeleteHotelAccount.as_view(), name='delete-hotel-account'),
    path('add-room-details/',AddRoomDetails.as_view(),name='add-room-details'),
    path('list-room-details-by-id/<int:id>/', ViewRoomDetailsById.as_view(), name='list-room-details-by-id'),
    path('list-hotel-room-details/', ViewHotelRoomDetails.as_view(), name='list-hotel-room-details'),
    path('list-hotel-room-details-by-status/<str:roomdetailstatus>/', RoomDetailsByStatus.as_view(), name='list-hotel-room-details-by-status'),
    path('admin-view-room-details/',AdminViewRoomDetails.as_view(),name='admin-view-room-details'),
    path('hotel-room-details/<int:hotel_id>/', ListHotelRoomDetails.as_view(), name='hotel-room-details'),
    path('review/<int:hotel_id>/',ReviewView.as_view(),name='review'),
    path('list-active-hotels/',ListActiveHotelDetails.as_view(),name='list-active-hotels'),
    path('select-hotels/',HotelSearchView.as_view(),name='select-hotels'),
    path('get-room-types/', GetRoomTypes.as_view(), name='get-room-types'),
    path('delete-room-details/<int:room_details_id>/', DeleteRoomDetails.as_view(), name='delete-room-details'),
    path('edit-hotel-details/', EditHotelDetails.as_view(), name='edit-hotel-details'),
    path('edit-room-details/<int:room_details_id>/', EditRoomDetails.as_view(), name='edit-room-details'),
    path('add-room-services/',AddRoomServices.as_view(),name='add-room-services'),
    path('add-feedbacks/<int:review_id>/', AddFeedbacksByHotels.as_view(), name='add-feedbacks'),
    path('list-reviews-by-hotels/', ListFeedbacksByHotels.as_view(), name='list-reviews-by-hotels'),
    path('view-room-services/', ViewRoomServices.as_view(), name='view-room-services'),
    path('add-room-additional-activities/<int:room_id>/<int:additional_activities_id>/',RoomAdditionalActivitesView.as_view(),name='add-room-additional-activities'),
    path('list-room-additional-activities/',ViewAdditionalActivitesByHotel.as_view(),name='list-room-additional-activities'),
    path('admin_list_activities_of_room/<int:room_id>/',ViewActivitiesAddedToRooms.as_view(), name='admin_list_activities_of_room'),
    path('hotel_list_activities_of_room/<int:room_id>/', ViewActivitiesAddedToRoomsByHotels.as_view(), name='hotel_list_activities_of_room'),
    path('hotel_delete_activities_of_room/<int:room_id>/<int:additional_activities_id>/', DeleteServicesAddedToRooms.as_view(), name='hotel_delete_activities_of_room'),
    path('book-hotel-room/', BookingHotelRoom.as_view(), name='book-hotel-room'),
    path('get-customer-booking/<int:booking_id>/', GetCustomerBookings.as_view(), name='get-customer-booking'),
    path('get-review/',GetReviewView.as_view(),name='get-review'),
    path('review-update/<int:review_id>/',UpdateReview.as_view(),name='review-update'),
    path('review-delete/<int:review_id>/',DeleteReview.as_view(),name='review-delete'),
    path('list-booking-details/', ListBookings.as_view(), name='list-booking-details'),
    path('sort-booking-details/<str:sort_by>/', SortBooking.as_view(), name='sort-booking-details'),
    path('edit-room-services/<int:room_services_id>/', EditRoomServices.as_view(), name='edit-room-services'),
    path('delete-room-services/<int:room_services_id>/',DeleteRoomServices.as_view(),name='delete-room-services'),
    path('list-services-by-id/<int:service_id>/', ViewServicesById.as_view(), name='list-services-by-id'),
    path('activate-hotel/<int:hotel_id>/',ActivateHotel.as_view(),name='activate-hotel'),
    path('payment-calculation/<int:booking_id>/', PaymentCalculation.as_view(), name='payment-calculation'),
    path('payment-confirmation/', PaymentConfirmation.as_view(), name='payment-confirmation'),
    path('create_payment_checkout/', StripePaymentCheckout.as_view(), name='create-payment-checkout'),   
    path('view-payment-details/<int:booking_id>/', ViewPaymentDetails.as_view(), name='view-payment-details'),
    path('payment_details/<int:booking_id>/', BookingPaymentDetails.as_view(), name='payment_details'),
    path('download_payment_invoice/<int:booking_id>/', PaymentInvoiceDetails.as_view(), name='download_payment_invoice'),
    path('reservation-list/', CustomerReservationList.as_view(), name='reservation-list'),
    path('sort-customer-reservation/<str:sort_by>/', SortCustomerReservation.as_view(), name='sort-customer-reservation'),
    path('today-booking-count/',CountTodayBooking.as_view(),name='today-booking-count'),
    path('payment-percentage/', PaymentPercentage.as_view(), name='payment-percentage'),
    path('selected-week-bookings/', GetSelectedWeekBookings.as_view(), name='selected-week-bookings'),    path('recent-reviews/', RecentReviews.as_view(), name='recent-reviews'),
    path('hotel-reviews-for-customer/<int:hotel_id>/', ReviewsListByHotelId.as_view(), name='hotel-reviews-for-customer'),
    path('cancel-bookings/<int:booking_id>/', CancelBookings.as_view(), name='cancel-bookings'),
    path('count-room-and-services/', RoomAndServicesCount.as_view(), name='count-room-and-services'),
    path('cancel-incomplete-bookings/<int:booking_id>/', CancelIncompleteBookings.as_view(), name='cancel-incomplete-bookings'),
    path('sort-active-hotels/',SortActiveHotelDetails.as_view(),name='sort-active-hotels'),
    path('hotel-notifications/', HotelNotifications.as_view(), name='hotel-notifications'),
    path('delete-hotel-notifications/<int:notification_id>/', DeleteHotelNotifications.as_view(), name='delete-hotel-notifications'),
    path('add-favorite-notification/<int:notification_id>/',AddHotelNotificationToFavorites.as_view(),name='add-favorite-notification'),
    path('read-hotel-notification/<int:notification_id>/',ReadHotelnotification.as_view(),name='read-hotel-notification'),
    path('unread-hotel-notification-count/',UnreadHotelNotificationCount.as_view(),name='unread-hotel-notification-count'),



]
