from django.urls import path
from user_app.views import (
    CustomerRegister,
    GetUserDetails,
    UserDetailsByStatus,
    EditUser,
    SuspendUser,
    DeleteUser,
    ViewCustomer,
    CreateSupervisor,
    VerifyEmail,
    LoginView,
    ForgotPasswordView,
    ResetPassword,
    ChangePasswordView,
    CheckTokenExpiredView,
    ListSupervisors,
    DeleteSuperVisor,
    DeleteCustomerAccount,
    ActivateCustomer,
    CountList,
    HotelBookingGraph,
    CountHotelStatus,
    HotelAverageRating,
    GetUserData,
    Adminnotifications,
    DeleteNotificationsAPIView,
    AddNotificationToFavorites,
    CustomerNotifications,
    DeleteCustomerNotifications,
    AddCustomerNotificationToFavorites,
    ReadCustomernotification,
    UnreadCustomerNotificationCount,
    ReadAdminNotification,
    UnreadAdminNotificationCount


) 

urlpatterns = [
        path('login/', LoginView.as_view(), name='login'),  
        path('customer-register/', CustomerRegister.as_view(), name='customer-register'),
        path('edit-customer/',EditUser.as_view(),name='edit-customer'), 
        path('customer-details/', GetUserDetails.as_view(), name='customer-details'),
        path('customers-by-status/<str:userstatus>/', UserDetailsByStatus.as_view(), name='customers-by-status'), 
        path('suspend-customer/<int:id>/', SuspendUser.as_view(), name='suspend-customer'),
        path('delete-customer/<int:id>/', DeleteUser.as_view(), name='delete-customer'),
        path('view-customer/<int:id>/',ViewCustomer.as_view(), name='view-customer'),
        path('create-supervisor/', CreateSupervisor.as_view(), name='create-supervisor'), 
        path('forgotpassword/',ForgotPasswordView.as_view(),name='forgotpassword'),
        path('resetpassword/<str:token>/',ResetPassword.as_view(),name='resetpassword'),
        path('checktokenexpiry/<str:token>/',CheckTokenExpiredView.as_view(),name='checktokenexpiry'),
        path('changepassword/',ChangePasswordView.as_view(),name='changepassword'),
        path('verify-email/<int:user_id>/', VerifyEmail.as_view(), name='verify-email'), 
        path('list-supervisors/', ListSupervisors.as_view(), name='list-supervisors'),
        path('delete-supervisor/<int:id>/', DeleteSuperVisor.as_view(), name='delete-supervisor'), 
        path('delete-customer-account/<int:customer_id>/', DeleteCustomerAccount.as_view(), name='delete-customer-account'),
        path('activate-customer/<int:customer_id>/',ActivateCustomer.as_view(),name='activate-customer'),
        path('count-list/',CountList.as_view(),name='count-list'),
        path('hotel-booking-graph/',HotelBookingGraph.as_view(),name='hotel-booking-graph'),
        path('count-list-hotels/',CountHotelStatus.as_view(),name='count-list-hotels'),
        path('most-reviewd-hotel/',HotelAverageRating.as_view(),name='most-reviewd-hotel'),
        path('get-user-data/',GetUserData.as_view(),name='get-user-data'),
        path('admin-notifications/',Adminnotifications.as_view(),name='admin-notifications'),
        path('delete-notifications/<int:notification_id>/', DeleteNotificationsAPIView.as_view(), name='delete-notifications'),
        path('add-favorite-notification/<int:notification_id>/',AddNotificationToFavorites.as_view(),name='add-favorite-notification'),
        path('customer-notifications/',CustomerNotifications.as_view(),name='customer-notifications'),
        path('delete-customer-notifications/<int:notification_id>/', DeleteCustomerNotifications.as_view(), name='delete-customer-notifications'),
        path('add-favorite-notification-customer/<int:notification_id>/',AddCustomerNotificationToFavorites.as_view(),name='add-favorite-notification-customer'),
        path('read-customer-notification/<int:notification_id>/',ReadCustomernotification.as_view(),name='read-customer-notification'),
        path('unread-customer-notification-count/',UnreadCustomerNotificationCount.as_view(),name='unread-customer-notification-count'),
        path('read-admin-notification/<int:notification_id>/',ReadAdminNotification.as_view(),name='read-admin-notification'),
        path('unread-admin-notification-count/',UnreadAdminNotificationCount.as_view(),name='unread-admin-notification-count'),

 

]
