# Generated by Django 5.0.1 on 2024-04-15 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('aadhar_number', models.BigIntegerField()),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='in progress', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location_link', models.CharField(max_length=2047, null=True)),
                ('status', models.CharField(default='inactive', max_length=100)),
                ('user_type', models.CharField(default='hotel', max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='room_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_email', models.CharField(default=None, max_length=250)),
                ('customer_name', models.CharField(default=None, max_length=250)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
                ('created_at', models.DateField(default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
                ('feedbacks', models.CharField(blank=True, max_length=250)),
                ('feedbacks_created_at', models.DateField(null=True)),
                ('feedbacks_updated_on', models.DateField(null=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='review_images/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAdditionalActivites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField(null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_on', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.BigIntegerField()),
                ('room_facilities', models.CharField(max_length=250)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
                ('booked_rooms', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, max_length=255, null=True, upload_to='room_images/')),
                ('image2', models.ImageField(blank=True, max_length=255, null=True, upload_to='room_images/')),
                ('image3', models.ImageField(blank=True, max_length=255, null=True, upload_to='room_images/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='services')),
                ('status', models.CharField(default='active', max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(null=True)),
            ],
        ),
    ]
